### ISSUE TITLE
Method getChartData does not exist

### ISSUE THREAD

**Issue by thuongtin** [pepijnolivier/laravel-bittrex#2]
How to get Chart Data guy?

**Comment by pepijnolivier** [comment]
@thuongtin 

You could do this in 2 ways. Since getting the chart data is a public method, you can just use the Facade.


```
$marketName = "BTC-SC";
$tickInterval = "hour"; // See Bittrex::getValidChartDataTickIntervals();
```

1. Facade approach
```
$chartData = Bittrex::getChartData($marketName, $tickInterval);
```

2. Via the client
```
$urls = config('bittrex.urls');
$auth = ['key' => "__your-api-key", 'secret' => "__your-api-secret"];
$client = new \Pepijnolivier\Bittrex\Client($auth, $urls);
$chartData = $client->getChartData($marketName, $tickInterval);
```

If you're using a decent IDE (PHPStorm), using the client has the benefit of code completion.
Check out Client.php for all the methods with documentation in docblocks.
I will update the readme with the `getChartData` method, thanks for pointing that out.

https://github.com/pepijnolivier/laravel-bittrex/blob/master/src/Client.php#L167

---

One thing to note though, `getChartData` uses API 2.0. This API is undocumented and might break at anytime.

**Comment by pepijnolivier** [comment]
@thuongtin I see now. I forgot to draft a new release back when I added these methods.
Running `composer update pepijnolivier/laravel-bittrex` should get you what you need.

Thanks!
